version: "3.5"

services:
  hserver0:
    image: hstreamdb/hstream:latest
    depends_on:
      zookeeper:
        condition: service_started
      hstore:
        condition: service_healthy
    ports:
      - "127.0.0.1:6570:6570"
    expose:
      - 6570
    networks:
      hstream-network:
        ipv4_address: 10.5.0.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - data_store:/data/store
    command:
      - bash
      - "-c"
      - |
        set -e
        /usr/local/script/wait-for-storage.sh hstore 6440 zookeeper 2181 600 \
        /usr/local/bin/hstream-server \
        --bind-address 0.0.0.0 --port 6570 \
        --internal-port 6571 \
        --server-id 100 \
        --seed-nodes "$$(hostname -I | awk '{print $$1}'):6571,hserver1:6573" \
        --advertised-address $$(hostname -I | awk '{print $$1}') \
        --metastore-uri zk://zookeeper:2181 \
        --store-config /data/store/logdevice.conf \
        --store-admin-host hstore --store-admin-port 6440 \
        --io-tasks-path /tmp/io/tasks \
        --io-tasks-network hstream-network

  hserver1:
    image: hstreamdb/hstream:latest
    depends_on:
      zookeeper:
        condition: service_started
      hstore:
        condition: service_healthy
    ports:
      - "127.0.0.1:6572:6572"
    expose:
      - 6572
    networks:
      hstream-network:
        ipv4_address: 10.5.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - data_store:/data/store
    command:
      - bash
      - "-c"
      - |
        set -e
        /usr/local/script/wait-for-storage.sh hstore 6440 zookeeper 2181 600 \
        /usr/local/bin/hstream-server \
        --bind-address 0.0.0.0 --port 6572 \
        --internal-port 6573 \
        --server-id 101 \
        --seed-nodes "hserver0:6571,$$(hostname -I | awk '{print $$1}'):6573" \
        --advertised-address $$(hostname -I | awk '{print $$1}') \
        --metastore-uri zk://zookeeper:2181 \
        --store-config /data/store/logdevice.conf \
        --store-admin-host hstore --store-admin-port 6440 \
        --io-tasks-path /tmp/io/tasks \
        --io-tasks-network hstream-network

  hserver-init:
    image: hstreamdb/hstream:latest
    depends_on:
      - hserver0
      - hserver1
    networks:
      hstream-network:
        ipv4_address: 10.5.0.7
    command:
      - bash
      - "-c"
      - |
        timeout=60
        until ( \
            /usr/local/bin/hadmin server --host hserver0 --port 6570 status && \
            /usr/local/bin/hadmin server --host hserver1 --port 6572 status \
        ) >/dev/null 2>&1; do
            >&2 echo 'Waiting for servers ...'
            sleep 1
            timeout=$$((timeout - 1))
            [ $$timeout -le 0 ] && echo 'Timeout!' && exit 1;
        done; \
        /usr/local/bin/hadmin server --host hserver0 init

  hstore:
    image: hstreamdb/hstream:latest
    networks:
      hstream-network:
        ipv4_address: 10.5.0.6
    volumes:
      - data_store:/data/store
    command:
      - bash
      - "-c"
      - |
        set -ex
        # N.B. "enable-dscp-reflection=false" is required for linux kernel which
        # doesn't support dscp reflection, e.g. centos7.
        /usr/local/bin/ld-dev-cluster --root /data/store \
        --use-tcp --tcp-host $$(hostname -I | awk '{print $$1}') \
        --user-admin-port 6440 \
        --param enable-dscp-reflection=false \
        --no-interactive \
        > /data/store/hstore.log 2>&1
    healthcheck:
      test: ["CMD", "grep", "LogDevice Cluster running", "/data/store/hstore.log"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s

  zookeeper:
    image: zookeeper
    expose:
      - 2181
    networks:
      - hstream-network
    volumes:
      - data_zk_data:/data
      - data_zk_datalog:/datalog

networks:
  hstream-network:
    name: hstream-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
volumes:
  data_store:
    name: hstreamdb_data_store
  data_zk_data:
    name: hstreamdb_data_zk_data
  data_zk_datalog:
    name: hstreamdb_data_zk_datalog
